apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aaaaa-clusterrole
rules:
  - verbs: [ "get", "watch", "list" ]
    nonResourceURLs:
      - /healthz
      - /livez
      - /readyz
