apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: pods-high
    spec:
      hard:
        requests.cpu: "1"
        requests.memory: 1Gi
        limits.cpu: "2"
        limits.memory: 2Gi
        cpu: "1000"
        memory: 200Gi
        pods: "10"
        requests.nvidia.com/gpu: "4"
{{/*        secrets: "100"*/}}
{{/*        services: "10"*/}}
{{/*        services.loadbalancers: "2"*/}}
{{/*        configmaps: "10"*/}}
{{/*        persistentvolumeclaims: "4"*/}}
{{/*        replicationcontrollers: "20"*/}}
      scopeSelector:
        matchExpressions:
          - operator : In
            scopeName: PriorityClass
            values: ["high"]
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: pods-medium
    spec:
      hard:
        cpu: "10"
        memory: 20Gi
        pods: "10"
      scopeSelector:
        matchExpressions:
          - operator : In
            scopeName: PriorityClass
            values: ["medium"]
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: pods-low
    spec:
      hard:
        cpu: "5"
        memory: 10Gi
        pods: "10"
      scopeSelector:
        matchExpressions:
          - operator : In
            scopeName: PriorityClass
            values: ["low"]