resource:
  group: elbv2.k8s.aws
  version: v1beta1
  kind: IngressClassParams
imports:
  - import "commons" as commons;
events:
  - !Submit
    action: ShowDetailsTemplate

details:
  template: ../detail/elbv2.ingressclassparams.hbs
  helpers:
    - name: will_table_fit_screen
      path: ./helpers/will_table_fit_screen.rhai

columns:
  - name: name
    display_name: Name
    width: 0
    evaluator: !Embedded
      name: Name

  - name: status
    display_name: Status
    width: 5
    evaluator: !Embedded
      name: Status

  - name: age
    display_name: Age
    width: 5
    evaluator: !Embedded
      name: Age
